#!/bin/bash

# These values need to be bumped when producing new RPMs
# version = version of software you are compiling
# iteration = the iteration number of the RPM you are producing
# NOTE: The RPM which is produced will overwrite the RPM on the S3 bucket on successful run
export version=1.3
export iteration=3

# Remove Gemfile.lock if it exists
if [ -f Gemfile.lock ]; then
  echo "Removing Gemfile.lock file... this could be handled by clearing jenkins workspace"
  rm -f Gemfile.lock
fi

# Source my jenkins config if available
if [ -f ~/.jenkins.sh ]; then
  source ~/.jenkins.sh
fi

if [ -f ~/.bash_profile ]; then
  source ~/.bash_profile
fi

# Set ruby version
RUBY_VERSION=2.1.1
echo RUBY_VERSION = $RUBY_VERSION
echo GIT_BRANCH = $GIT_BRANCH

# Install ruby version
rbenv install --skip-existing $RUBY_VERSION
rbenv rehash

# Function to cleanup any running instances and exit
function clean_up_and_exit {
  echo "--- Cleaning Up Build Instances ---"
  ruby ./script/cleanup.rb

  echo "--- Build Completed With Status $1 ---"
  exit $1
}

# Install bundler
gem install bundler --no-ri --no-rdoc

# Run bundle
bundle install

if [ $? -ne 0 ]; then
  clean_up_and_exit 1
fi

# Create an instance
knife ec2 server create -c ./script/knife/config/knife.rb \
                        --template-file ./script/knife/templates/omnibus.erb \
                        --groups=build \
                        --node-name='intu-aws-cfn-bootstrap-omnibus-build'
if [ $? -ne 0 ]; then
  clean_up_and_exit 1
fi

clean_up_and_exit 0
