#!/bin/bash

# Source my jenkins config if available
if [ -f ~/.jenkins.sh ]; then
  . ~/.jenkins.sh
fi

# Function to cleanup any running instances and exit
function clean_up_and_exit {
  echo "--- Cleaning Up Build Instances ---"
  ruby ./script/cleanup.rb

  echo "--- Build Completed With Status $1 ---"
  exit $1
}

# Set Ruby / Gemset
rvm use 2.0.0-p247@omnibus-intu-aws-cfn-bootstrap --create

# Install knife ec2
gem install knife-ec2 --no-ri --no-rdoc --quiet
if [ $? -ne 0 ]; then
  clean_up_and_exit 1
fi

# Create an instance
knife ec2 server create -c ./script/knife/config/knife.rb \
                        --template-file ./script/knife/templates/omnibus.erb \
                        --groups=build \
                        --node-name='intu-aws-cfn-bootstrap-omnibus-build'
if [ $? -ne 0 ]; then
  clean_up_and_exit 1
fi

clean_up_and_exit 0
